/**
  ******************************************************************************
  * @file           : rng.c
  * @author         : Dr. Joshua Butler
  * @date           : Dec 9, 2024
  * @brief          : Random number generator for selecting the next tetrimino
  ******************************************************************************
  * @attention
  *
  * 2025 Imagine RIT Project: Classic Tetris on LED Grid
  *
  * Copyright (c) 2024-25 Rochester Institute of Technology.
  * All rights reserved.
  *
  * This software is licensed under terms that can be found in the LICENSE file
  * in the root directory of this software component.
  * If no LICENSE file comes with this software, it is provided AS-IS.
  *
  ******************************************************************************
  */

/**
 ********************************************************************************
 * Use the algorithm given in the https://meatfighter.com/nintendotetrisai/ article
 *
 * Each successive pseudorandom number is generated by treating the value as a
 * 17-bit number and setting the highest bit to the result of XORing bits 1 and 9
 * together. Then, the value is right shifted, tossing away the lowest bit.
 *
 * It uses Linear Feedback Shift Register (LFSR) algorithm to generate random numbers.
 *
 * The algorithm gives balanced choices for the next tetrimino.
 */


#include <stdint.h>
#include "rng.h"

static uint32_t rng_seed = 0;

/**
 * @brief  Initialize random number generator
 * @param  seeding value
 * @retval None
 */
void rng_init(void) {
    // TODO: Initialize random number generator
}

/**
 * @brief  Compute the next random number
 * @param  None
 * @retval next chosen tetrimino identifier
 */
uint8_t rng_next(void) {
    // TODO: Compute the next random number using LFSR algorithm from the seeding value
    return rng_seed;
}
